### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by NotDiamondZ**
Screenshot 2021-05-20 4 41 52 PM
As you can see in the photo, the logo is squished. We can fix this by removing the height.

### CODE REVIEW

**Comment by NotDiamondZ** [comment]
cc @brourbeinsus

**Comment by brourbeinsus** [comment]
Two things

- I’m still setting up the website so you really don’t need to pull request
- I know that and that is what I’m fixing right now

**Comment by NotDiamondZ** [comment]
> Two things
> 
> * I’m still setting up the website so you really don’t need to pull request
> * I know that and that is what I’m fixing right now

You've been setting it up for like 5 hours. I'd be done by then.

**Comment by brourbeinsus** [comment]
You don’t need to rush me, I can work at my own pace. I should be done in less then a day or two.

**Comment by NotDiamondZ** [comment]
cool

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by brourbeinsus** [comment]
Ok! Website is finished! Took a lot shorter than I thought it would...

**Comment by xItzDiamondx** [comment]
Great. Can you inv now?

**Comment by brourbeinsus** [comment]
Yeah, you wanted me to add @NotDiamondZ right?

**Comment by xItzDiamondx** [comment]
Correct.

**Comment by NotDiamondZ** [comment]
Hello?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by brourbeinsus** [comment]
Ok I added you but this is like a video game, you gotta work up the ranks, if you make enough good PRs I’ll give you write access.

**Comment by brourbeinsus** [comment]
Your welcome, also make sure to deploy your fork to GitHub pages so I can test your PRs

**Pull request closed without merging**
